<?php

declare(strict_types = 1);

namespace Amondar\Postman\Blueprints;

use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Support\Carbon;

/**
 * Class FileInfo
 *
 * @implements Arrayable<string, ?string>
 *
 * @author Amondar-SO
 */
final readonly class FileInfo implements Arrayable
{
    public string $description;

    /**
     * FileInfo constructor.
     */
    public function __construct(
        public string $name,
        ?string $description = null,
        public string $schema = 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    ) {
        if ($description === null) {
            $this->description = "Generated by Amondar's Postman Collection at " . Carbon::now()->format('F j, Y \a\t H:i:s e');
        } else {
            $this->description = $description;
        }
    }

    /**
     * Get the instance as an array.
     *
     * @return array<string, ?string>
     */
    public function toArray(): array
    {
        return [
            'name'        => $this->name,
            'description' => $this->description,
            'schema'      => $this->schema,
        ];
    }
}
