<?php

declare(strict_types = 1);

namespace Amondar\Postman\Commands;

use Amondar\Postman\Contracts\RouteParserContract;
use Amondar\Postman\Export;
use Amondar\Postman\Laravel\LaravelRoutesParser;
use Amondar\Postman\Route\RouteCollection;
use Amondar\Postman\Route\RouteFilter;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

use function Termwind\ask;
use function Termwind\render;
use function Termwind\renderUsing;

/**
 * Class ExportCommand
 *
 * @author Amondar-SO
 */
#[AsCommand(name: 'export', description: 'Export project routes to a Postman collection')]
final class ExportCommand extends Command
{
    /**
     * Executes the command.
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        renderUsing($output);

        $routes = $this->getFilteredRoutes(
            $input,
            $this->getRoutesCollection($input)
        );
        $lookAttributesIn = $input->getOption('attributes-in') ?? [];
        $baseUrl = $input->getOption('base-url') ?? 'https://example.com';
        $oauthTokenUrl = $input->getOption('oauth-token-url');
        $name = $input->getOption('collection-name') ?? 'postman.json';
        $description = $input->getOption('collection-description');
        $toFile = $input->getOption('output');
        $headers = $this->normalizeAssociative($input->getOption('headers'));
        $variables = $this->normalizeAssociative($input->getOption('variables'));

        if ($routes === null) {
            render(
                <<<'HTML'
                <span class="mt-1 ml-2 mr-1 bg-red px-1 text-black">
                    Routes collection isn’t found or could not be parsed.
                </span>
            HTML
            );

            return Command::FAILURE;
        }

        $response = Export::from($routes, $baseUrl)
            ->when(
                $oauthTokenUrl !== null,
                fn(Export $exporter) => $exporter->useOAuthTokenPath($oauthTokenUrl)
            )
            ->withGlobalHeaders($headers)
            ->withGlobalVariables($variables)
            ->parseDataIn(...$lookAttributesIn)
            ->toJson($name, $description, $this->getJsonOptions($input), 100);

        if ($toFile) {
            file_put_contents($toFile, $response);
        } else {
            $output->write($response);
        }

        return Command::SUCCESS;
    }

    /**
     * Configures the current command.
     */
    protected function configure(): void
    {
        $this
            ->addOption('laravel', null, InputOption::VALUE_NONE, 'Indicates that we have Laravel project.')
            ->addOption(
                'routes-parser',
                'parser',
                InputOption::VALUE_REQUIRED,
                'The full namespace path to the routes parser class.'
            )
            ->addOption(
                'attributes-in',
                'attributes',
                InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
                'List of passes, where we should look for classes, that apply package attributes.'
            )
            ->addOption(
                'collection-name',
                'name',
                InputOption::VALUE_REQUIRED,
                'The name of the Postman collection. By default: postman.json'
            )
            ->addOption(
                'collection-description',
                'description',
                InputOption::VALUE_REQUIRED,
                'The description of the Postman collection. By default: "Generated by Amondar\'s Postman Collection at {DATE_TIMESTAMP_HERE}"'
            )
            ->addOption(
                'base-url',
                'url',
                InputOption::VALUE_REQUIRED,
                'Base url for the requests. Will be set as {{base_url}} global variable.'
            )
            ->addOption(
                'oauth-token-url',
                'oauth-url',
                InputOption::VALUE_REQUIRED,
                'Base url for the OAuth requests. Will be set as {{oauth_full_url}} global variable. Should be something like "/oauth/token". If relative path provided, then will be prefixed with base url variable.'
            )
            ->addOption(
                'headers',
                'H',
                InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
                'Additional headers to be sent with each request. Example: --headers="X-Custom-Header: my-custom-header".'
            )
            ->addOption(
                'variables',
                'VR',
                InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
                'Additional variables to be sent on collection. Example: --variables="my_var: my-value". Then in the collection you can use {{my_var}} variable.'
            )
            ->addOption(
                'route-paths',
                'paths',
                InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
                'Filter routes by given paths. Can be passed inline separated by semicolon.'
            )
            ->addOption(
                'route-names',
                'names',
                InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
                'Filter routes by given names. Can be passed inline separated by semicolon.'
            )
            ->addOption(
                'route-methods',
                'methods',
                InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
                'Filter routes by given methods. Can be passed inline separated by semicolon.'
            )
            ->addOption(
                'route-middlewares',
                'middlewares',
                InputOption::VALUE_REQUIRED | InputOption::VALUE_IS_ARRAY,
                'Filter routes by given middlewares. Can be passed inline separated by semicolon.'
            )
            ->addOption(
                'route-affected-only',
                'affected-only',
                InputOption::VALUE_NONE,
                'Filter routes that are affected by the package. E.g. routes that have package attributes - alias, description, etc.'
            )
            ->addOption(
                'output',
                null,
                InputOption::VALUE_REQUIRED,
                'Path to the file where the exported collection will be saved.'
            )
            ->addOption(
                'format',
                null,
                InputOption::VALUE_REQUIRED,
                'Define the output format. By default: json. Available formats: json, pretty-json.'
            );
    }

    protected function getRoutesCollection(InputInterface $input): ?RouteCollection
    {
        if ($input->getOption('laravel')) {
            return (new LaravelRoutesParser)->parse(base_path());
        }

        $class = null;

        while ($class === null) {
            $class = $input->getOption('routes-parser');

            if ($class === null && $input->getOption('no-interaction') === true) {
                break;
            }

            $class = ask(
                <<<'HTML'
                    <div class="ml-2 mt-1">
                        <span class="text-gray-300">
                            <span class="bg-green px-1 text-black font-bold">
                                What is
                            </span>
                            <span class="ml-1">
                                the routes parser class?<br>&nbsp;&nbsp;
                            </span>
                        </span>
                    </div>
                HTML
            );
        }

        if ( ! class_exists($class)) {
            render(
                <<<HTML
                <span class="mt-1 ml-2 mr-1 bg-red px-1 text-black">
                    Class [$class] does not exist.
                </span>
            HTML
            );

            return null;
        }

        if ( ! in_array(RouteParserContract::class, class_implements($class))) {
            render(
                <<<HTML
                <span class="mt-1 ml-2 mr-1 bg-red px-1 text-black">
                    Class [$class] does not implement [<b>RouteParserContract</b>].
                </span>
            HTML
            );

            return null;
        }

        return (new $class)->parse($this->getPredictedProjectRoot());
    }

    protected function getPredictedProjectRoot(): string
    {
        $start = getcwd() ?: __DIR__;
        $dir = realpath($start) ?: $start;

        while ($dir !== '' && $dir !== DIRECTORY_SEPARATOR) {
            if (is_file($dir . '/composer.json')) {
                return $dir;
            }

            $parent = dirname($dir);

            if ($parent === $dir) {
                break;
            }

            $dir = $parent;
        }

        return $start;
    }

    protected function getJsonOptions(InputInterface $input): int
    {
        if ($input->getOption('format') === 'pretty-json') {
            return JSON_PRETTY_PRINT;
        }

        return 0;
    }

    protected function getFilteredRoutes(InputInterface $input, ?RouteCollection $routes): ?RouteCollection
    {
        if ($routes === null || $routes->isEmpty()) {
            return null;
        }

        $filters = (new Collection($input->getOptions()))
            ->filter(fn($value, $key) => Str::startsWith($key, 'route-'))
            ->mapWithKeys(fn($value, $key) => [$key => is_array($value) ? $this->prepareFilterValues($value) : $value])
            ->filter();

        $filter = RouteFilter::apply()
            ->when($filters->has('route-affected-only'), fn(RouteFilter $filter) => $filter->affectedByPackage())
            ->when($filters->has('route-paths'), fn(RouteFilter $filter) => $filter->byPath($filters->get('route-paths')))
            ->when($filters->has('route-names'), fn(RouteFilter $filter) => $filter->byName($filters->get('route-names')))
            ->when($filters->has('route-methods'), fn(RouteFilter $filter) => $filter->byMethod($filters->get('route-methods')))
            ->when($filters->has('route-middlewares'), fn(RouteFilter $filter) => $filter->byMiddleware($filters->get('route-middlewares')));

        /** @noinspection PhpIncompatibleReturnTypeInspection */
        return $routes->filterRoutes($filter)->values();
    }

    protected function prepareFilterValues(array $values): array
    {
        return (new Collection($values))
            ->map(fn($value) => Str::of($value)->explode(';'))
            ->flatten()
            ->toArray();
    }

    protected function normalizeAssociative(array $input): array
    {
        return (new Collection($input))
            ->map(function ($value) {
                $pair = explode(':', $value);

                return [mb_trim($pair[0]), mb_ltrim($pair[1] ?? '')];
            })
            ->mapWithKeys(fn($pair) => [$pair[0] => $pair[1]])
            ->toArray();
    }
}
